"""Weekly aggregation of daily operational data (PRD-05 §2).

This module is the **canonical rollup layer** of the operational
package. It aggregates up to seven days of :class:`DailyLog` or
:class:`DailyConsolidation` records into a single
:class:`WeeklyAggregate` for the trailing 7-day window.

Source spec:

* **PRD-05** ``vibe-ops/planning/PRD-05-metrics-health.md`` §2 —
  :class:`WeeklyAggregate` shape, score formula, week-label buckets.
* **PRD-05** §2.6 — week-score ranges (``0.0, 100.0``) and the
  :class:`WeekLabel` mapping (delegated to the
  :class:`operational.entities.consolidation.WeeklyAggregate` model).

The aggregator is **stateless** apart from its dataclass fields; the
:class:`WeeklyAggregator` wrapper is a thin namespace class that
exposes the two aggregation methods. The module-level
:func:`aggregate_week` is a convenience function for callers that do
not need to instantiate the wrapper.

Aggregation rules (PRD-05 §2.6):

* ``avg_sleep_hours`` — mean of :attr:`DailyLog.sleep.duration_hours`
  over days that have a :class:`SleepRecord`. ``0.0`` if no day has
  a sleep record.
* ``avg_sleep_quality`` — mean of :attr:`SleepRecord.quality_score`
  (1-10). ``5.0`` (midpoint) if no day has a sleep record.
* ``avg_energy_score`` — mean of :attr:`DailyLog.avg_energy` (0-100)
  over days with at least one energy reading. ``0.0`` if no day has
  readings.
* ``avg_productivity`` — for ``aggregate_from_consolidations``,
  mean of :attr:`DailyConsolidation.productivity_score` (0-100).
  Always ``0.0`` for ``aggregate_from_logs`` (not derivable from
  the log alone).
* ``total_tasks_done`` — sum of :attr:`DailyLog.tasks_completed`.
* ``total_study_minutes`` — sum of :attr:`DailyLog.study_minutes`.
* ``total_exercise_days`` — count of days with
  :attr:`DailyLog.exercise_done == True`.
* ``habit_compliance_avg`` — mean of
  :attr:`DailyLog.habit_compliance_pct` (0-100).
* ``week_score`` — for logs: ``min(100, total_pomodoros / 60 * 100)``
  (60 = target pomodoros per week, ~8.6/day). For consolidations:
  the mean of :attr:`DailyConsolidation.overall_score`.

Design rules:

* **Pure functions** — no I/O, no state mutation, no logging side
  effects. The :class:`WeeklyAggregator` is a thin namespace
  class (no instance state) — see Sprint 3 conventions
  (:class:`SleepQuality` precedent).
* **mypy --strict** compatible — every parameter and return type
  is annotated.
* **ruff ALL** compliant — line-length 100, Google docstrings,
  no emojis in code.
* No imports from sibling :mod:`operational.core` modules to avoid
  circular dependencies. The aggregator imports from
  :mod:`operational.entities.metric` and
  :mod:`operational.entities.consolidation` (both leaves).
* All magic numbers are extracted to ``_CONSTANT`` ``Final`` vars.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, date, datetime, timedelta
from typing import TYPE_CHECKING, Final
from uuid import uuid4

from operational.entities.consolidation import WeeklyAggregate

if TYPE_CHECKING:
    from operational.entities.consolidation import DailyConsolidation
    from operational.entities.metric import DailyLog

__all__ = [
    "WEEKLY_POMODORO_TARGET",
    "WeeklyAggregator",
    "aggregate_week",
]


# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------

#: Number of days in a weekly aggregate window (PRD-05 §2.6). A
#: calendar week has 7 days but the aggregation accepts up to 7
#: (incomplete weeks are allowed).
WEEK_DAYS: Final[int] = 7

#: Target pomodoros per week used to compute the week-score for the
#: :meth:`WeeklyAggregator.aggregate_from_logs` path. Sourced from
#: PAV §1 (``POMODORO_ROUNDS_MAX=4`` x ~3 work blocks x 5 working
#: days). Exposed as a public constant for downstream consumers
#: (e.g. CLI progress bars) that need the same anchor.
WEEKLY_POMODORO_TARGET: Final[int] = 60

#: Default sleep-quality midpoint used when no day in the week has
#: a :class:`operational.entities.metric.SleepRecord`. Matches the
#: :class:`WeeklyAggregate` field default (``avg_sleep_quality=5.0``).
_DEFAULT_SLEEP_QUALITY: Final[float] = 5.0

#: Target sleep duration used to derive ``avg_sleep_hours`` from
#: sleep-debt when only consolidations are available.
#: Mirrors the entity-layer default of 8.0 hours but is kept as a
#: separate constant here to avoid importing private names from
#: the entity module.
_TARGET_SLEEP_HOURS: Final[float] = 8.0

#: ID prefix for weekly aggregate entities generated by the aggregator.
#: Must be 3-5 letters to match the :data:`operational.types.UEID`
#: pattern (``^[a-z]{3,5}_[a-z0-9_]+$``). The 3-letter ``"wkl"`` is
#: the canonical convention documented on
#: :class:`operational.entities.consolidation.WeeklyAggregate`.
_WEEK_ID_PREFIX: Final[str] = "wkl_"

#: Length of the hex slug appended to the ID prefix. 12 hex chars
#: gives ~48 bits of entropy — enough for a single week of aggregates.
_ID_HEX_LENGTH: Final[int] = 12


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _utc_now_naive() -> datetime:
    """Return the current wall-clock time as a naive UTC ``datetime``.

    Naive datetimes are used throughout the ``operational`` package so
    that Pydantic models serialise cleanly to JSON/SQLite TEXT columns
    without timezone arithmetic. The :class:`datetime.datetime.now`
    call passes ``tz=UTC`` so the linter does not complain
    (``DTZ005``); the result is then stripped to a naive datetime.
    """
    return datetime.now(UTC).replace(tzinfo=None)


# ---------------------------------------------------------------------------
# WeeklyAggregator
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class WeeklyAggregator:
    """Stateless weekly aggregator (PRD-05 §2.6).

    The class is a **namespace** — it carries no instance state and
    exposes two pure aggregation methods. The
    :func:`aggregate_week` module-level function is provided as an
    ergonomic alias for callers that do not need to instantiate
    the wrapper.

    Use the class form when you want a stable identity to pass around
    (e.g. in DI containers) and the function form for one-shot
    aggregations.
    """

    def aggregate_from_logs(
        self,
        week_start: date,
        logs: list[DailyLog],
    ) -> WeeklyAggregate:
        """Aggregate up to seven :class:`DailyLog` entries into a weekly summary.

        Args:
            week_start: Monday of the week (inclusive). The resulting
                ``week_end`` is computed as ``week_start + 6 days``.
            logs: List of :class:`DailyLog` records for the week, in
                any order. Must contain at most 7 entries. An empty
                list yields a zero-valued aggregate.

        Returns:
            A fully-populated :class:`WeeklyAggregate`. The ``days``
            field is **empty** (DailyLog IDs are not always
            discoverable here; the caller can populate them by
            re-creating the model with the desired IDs).

        Raises:
            ValueError: If ``logs`` contains more than 7 entries.
        """
        if len(logs) > WEEK_DAYS:
            msg = f"logs must be <= {WEEK_DAYS}, got {len(logs)}"
            raise ValueError(msg)

        week_end = week_start + timedelta(days=WEEK_DAYS - 1)
        now = _utc_now_naive()

        if not logs:
            return _empty_weekly(week_start, week_end, now)

        # Sleep metrics
        sleep_durations = [
            log.sleep.duration_hours for log in logs if log.sleep is not None
        ]
        avg_sleep_hours = (
            sum(sleep_durations) / len(sleep_durations) if sleep_durations else 0.0
        )
        sleep_qualities = [
            log.sleep.quality_score for log in logs if log.sleep is not None
        ]
        avg_sleep_quality = (
            sum(sleep_qualities) / len(sleep_qualities)
            if sleep_qualities
            else _DEFAULT_SLEEP_QUALITY
        )

        # Energy metrics (0-100)
        energy_scores = [log.avg_energy for log in logs if log.avg_energy is not None]
        avg_energy_score = (
            sum(energy_scores) / len(energy_scores) if energy_scores else 0.0
        )

        # Counters
        total_tasks_done = sum(log.tasks_completed for log in logs)
        total_study_minutes = sum(log.study_minutes for log in logs)
        total_exercise_days = sum(1 for log in logs if log.exercise_done)
        total_pomodoros = sum(log.pomodoros for log in logs)
        compliance_values = [log.habit_compliance_pct for log in logs]
        habit_compliance_avg = sum(compliance_values) / len(compliance_values)

        # Week score: pomodoros-based, capped at 100.
        week_score = min(100.0, (total_pomodoros / WEEKLY_POMODORO_TARGET) * 100.0)

        return WeeklyAggregate(
            id=f"{_WEEK_ID_PREFIX}{uuid4().hex[:_ID_HEX_LENGTH]}",
            week_start=week_start,
            week_end=week_end,
            days=[],
            avg_sleep_hours=avg_sleep_hours,
            avg_sleep_quality=avg_sleep_quality,
            avg_energy_score=avg_energy_score,
            avg_productivity=0.0,  # not derivable from DailyLog alone
            total_tasks_done=total_tasks_done,
            total_study_minutes=total_study_minutes,
            total_exercise_days=total_exercise_days,
            habit_compliance_avg=habit_compliance_avg,
            week_score=week_score,
            created_at=now,
        )

    def aggregate_from_consolidations(
        self,
        week_start: date,
        consolidations: list[DailyConsolidation],
    ) -> WeeklyAggregate:
        """Aggregate up to seven :class:`DailyConsolidation` entries.

        Args:
            week_start: Monday of the week (inclusive). The resulting
                ``week_end`` is computed as ``week_start + 6 days``.
            consolidations: List of :class:`DailyConsolidation`
                records for the week, in any order. Must contain at
                most 7 entries. An empty list yields a zero-valued
                aggregate with the ``days`` field empty.

        Returns:
            A fully-populated :class:`WeeklyAggregate`. The ``days``
            field is populated with the consolidation IDs in the
            order they were provided.
        """
        week_end = week_start + timedelta(days=WEEK_DAYS - 1)
        now = _utc_now_naive()

        if not consolidations:
            return _empty_weekly(week_start, week_end, now)

        # Averages
        n = len(consolidations)
        avg_energy = sum(c.energy_score for c in consolidations) / n
        avg_productivity = sum(c.productivity_score for c in consolidations) / n
        avg_health = sum(c.health_score for c in consolidations) / n
        avg_overall = sum(c.overall_score for c in consolidations) / n

        # Approximate avg_sleep_hours = target - avg_sleep_debt.
        avg_sleep_debt = sum(c.sleep_debt_hours for c in consolidations) / n
        avg_sleep_hours = _TARGET_SLEEP_HOURS - avg_sleep_debt

        return WeeklyAggregate(
            id=f"{_WEEK_ID_PREFIX}{uuid4().hex[:_ID_HEX_LENGTH]}",
            week_start=week_start,
            week_end=week_end,
            days=[c.id for c in consolidations],
            avg_sleep_hours=avg_sleep_hours,
            avg_sleep_quality=_DEFAULT_SLEEP_QUALITY,
            avg_energy_score=avg_energy,
            avg_productivity=avg_productivity,
            total_tasks_done=0,
            total_study_minutes=0,
            total_exercise_days=0,
            habit_compliance_avg=avg_health,
            week_score=avg_overall,
            created_at=now,
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _empty_weekly(
    week_start: date,
    week_end: date,
    created_at: datetime,
) -> WeeklyAggregate:
    """Build a zero-valued :class:`WeeklyAggregate`.

    Centralised here so both aggregation methods can return the same
    shape for an empty input. All numeric fields use their model's
    declared defaults; the ``id`` is generated here, the ``days``
    list is empty, and ``created_at`` is the supplied timestamp.

    Args:
        week_start: Monday of the week.
        week_end: Sunday of the week (``week_start + 6 days``).
        created_at: Wall-clock timestamp for the ``created_at`` field.

    Returns:
        A :class:`WeeklyAggregate` with the canonical zero defaults.
    """
    return WeeklyAggregate(
        id=f"{_WEEK_ID_PREFIX}{uuid4().hex[:_ID_HEX_LENGTH]}",
        week_start=week_start,
        week_end=week_end,
        days=[],
        created_at=created_at,
    )


# ---------------------------------------------------------------------------
# Module-level convenience function
# ---------------------------------------------------------------------------


def aggregate_week(
    week_start: date,
    logs: list[DailyLog] | None = None,
    consolidations: list[DailyConsolidation] | None = None,
) -> WeeklyAggregate:
    """Aggregate a week of data, dispatching on the input type.

    Provide **exactly one** of ``logs`` and ``consolidations``:

    * ``logs`` — dispatches to
      :meth:`WeeklyAggregator.aggregate_from_logs`.
    * ``consolidations`` — dispatches to
      :meth:`WeeklyAggregator.aggregate_from_consolidations`.

    If both are provided, ``logs`` wins (the more granular source).
    If neither is provided, a :class:`ValueError` is raised.

    Args:
        week_start: Monday of the week (inclusive).
        logs: Optional list of :class:`DailyLog` records.
        consolidations: Optional list of :class:`DailyConsolidation`
            records.

    Returns:
        A fully-populated :class:`WeeklyAggregate`.

    Raises:
        ValueError: If neither ``logs`` nor ``consolidations`` is
            provided.
    """
    aggregator = WeeklyAggregator()
    if logs is not None:
        return aggregator.aggregate_from_logs(week_start, logs)
    if consolidations is not None:
        return aggregator.aggregate_from_consolidations(week_start, consolidations)
    msg = "aggregate_week requires either logs or consolidations"
    raise ValueError(msg)
