param(
    [string]$RepoPath = ".",
    [string]$HookType = "post-commit"
)

# Resolve full paths
$RepoFullPath = Resolve-Path $RepoPath
$GitHooksPath = Join-Path $RepoFullPath ".git\hooks"
$VibeOpsPath = Join-Path $RepoFullPath "vibe-ops"
$TelemetryScript = Join-Path $VibeOpsPath "scripts\audit_github_execution.ps1"

if (-not (Test-Path $GitHooksPath)) {
    Write-Error "Could not find .git\hooks directory at $RepoFullPath. Make sure you run this from the root of a git repository."
    exit 1
}

$HookFile = Join-Path $GitHooksPath $HookType

# Create the bash hook script (git hooks run in a sh environment usually, even on Windows with MSYS)
$HookContent = @"
#!/bin/sh
# Auto-generated by setup_git_telemetry_hook.ps1
# Gathers GitHub execution telemetry on commit to update Daily Knowledge Reports

echo "Running Vibe-Ops Knowledge Telemetry..."
# Call the powershell script in the background so it doesn't block the commit
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$($TelemetryScript.ToString().Replace('\', '/'))" -RepoPath "$($RepoFullPath.ToString().Replace('\', '/'))" > /dev/null 2>&1 &
"@

Set-Content -Path $HookFile -Value $HookContent -Encoding utf8
Write-Host "Successfully installed $HookType hook at $HookFile"
Write-Host "Telemetry script will now run automatically on every commit."
