// Package report renders health/review/pattern results into shareable
// formats: text, markdown, JSON, SARIF, and HTML.
package report

import (
	"encoding/json"
	"fmt"
	"html"
	"strings"

	"github.com/life-oss/medic/internal/health"
	"github.com/life-oss/medic/internal/pattern"
	"github.com/life-oss/medic/internal/review"
)

// Format is the output format.
type Format string

const (
	FormatText     Format = "text"
	FormatMarkdown Format = "markdown"
	FormatJSON     Format = "json"
	FormatSARIF    Format = "sarif"
	FormatHTML     Format = "html"
)

// Bundle is a multi-section report payload.
type Bundle struct {
	Health   *health.Report      `json:"health,omitempty"`
	Review   *review.Report      `json:"review,omitempty"`
	Patterns []pattern.Finding   `json:"patterns,omitempty"`
}

// Render dispatches to the correct format.
func Render(b Bundle, format Format) (string, error) {
	switch format {
	case FormatText:
		return RenderText(b), nil
	case FormatMarkdown:
		return RenderMarkdown(b), nil
	case FormatJSON:
		data, err := json.MarshalIndent(b, "", "  ")
		return string(data), err
	case FormatSARIF:
		if b.Review != nil {
			return review.ReportSARIF(b.Review), nil
		}
		return `{"runs":[]}`, nil
	case FormatHTML:
		return RenderHTML(b), nil
	}
	return "", fmt.Errorf("unknown format %q", format)
}

// RenderText is the human-friendly terminal output.
func RenderText(b Bundle) string {
	var sb strings.Builder
	if b.Health != nil {
		sb.WriteString(health.FormatPretty(b.Health))
		sb.WriteString("\n")
	}
	if b.Review != nil {
		sb.WriteString(review.ReportMarkdown(b.Review))
		sb.WriteString("\n")
	}
	if len(b.Patterns) > 0 {
		sb.WriteString(pattern.FormatTable(b.Patterns))
	}
	return sb.String()
}

// RenderMarkdown is a single concatenated MD doc.
func RenderMarkdown(b Bundle) string {
	var sb strings.Builder
	if b.Health != nil {
		fmt.Fprintf(&sb, "## Health\n\n```\n%s\n```\n\n", health.FormatPretty(b.Health))
	}
	if b.Review != nil {
		sb.WriteString(review.ReportMarkdown(b.Review))
		sb.WriteString("\n")
	}
	if len(b.Patterns) > 0 {
		fmt.Fprintf(&sb, "## Patterns (%d)\n\n", len(b.Patterns))
		fmt.Fprintf(&sb, "| Family | Severity | Rule | Title |\n|---|---|---|---|\n")
		for _, p := range b.Patterns {
			fmt.Fprintf(&sb, "| %s | %s | %s | %s |\n", p.Family, p.Severity, p.Rule, p.Title)
		}
	}
	return sb.String()
}

// RenderHTML is a self-contained doc you can open in a browser.
func RenderHTML(b Bundle) string {
	var sb strings.Builder
	sb.WriteString(`<!doctype html><html><head><meta charset="utf-8"><title>medic report</title>`)
	sb.WriteString(`<style>
body{font-family:system-ui,sans-serif;max-width:920px;margin:24px auto;padding:0 16px;color:#111}
h1,h2,h3{border-bottom:1px solid #eee;padding-bottom:4px}
table{border-collapse:collapse;width:100%}
td,th{border:1px solid #ddd;padding:6px;text-align:left;font-size:14px}
tr:nth-child(even){background:#fafafa}
.tag{display:inline-block;padding:2px 8px;border-radius:4px;font-size:12px;color:#fff}
.tag.crit{background:#b91c1c} .tag.high{background:#dc2626} .tag.med{background:#d97706}
.tag.low{background:#0ea5e9} .tag.info{background:#475569}
pre{background:#0f172a;color:#e2e8f0;padding:12px;border-radius:6px;overflow:auto}
.ok{color:#16a34a} .warn{color:#d97706} .fail{color:#b91c1c}
</style></head><body>`)
	fmt.Fprintf(&sb, "<h1>medic 🩺 report</h1>")
	fmt.Fprintf(&sb, "<p>Generated by <code>medic</code>.</p>")
	if b.Health != nil {
		fmt.Fprintf(&sb, "<h2>Health <span class='%s'>%d/100</span></h2>", okClass(b.Health.OK), b.Health.Score)
		fmt.Fprintf(&sb, "<table><tr><th>Check</th><th>Kind</th><th>Severity</th><th>Detail</th></tr>")
		for _, c := range b.Health.Checks {
			fmt.Fprintf(&sb, "<tr><td>%s</td><td>%s</td><td><span class='tag %s'>%s</span></td><td>%s</td></tr>",
				html.EscapeString(c.Name), c.Kind, sevClass(string(c.Severity)), c.Severity, html.EscapeString(c.Err))
		}
		sb.WriteString("</table>")
	}
	if b.Review != nil {
		fmt.Fprintf(&sb, "<h2>Review #%d — %s</h2>", b.Review.PR.Number, html.EscapeString(b.Review.PR.Title))
		fmt.Fprintf(&sb, "<p><b>Verdict:</b> <span class='%s'>%s</span> · <b>Score:</b> %d/100</p>",
			verdictClass(string(b.Review.Verdict)), b.Review.Verdict, b.Review.Score)
		if len(b.Review.Findings) > 0 {
			fmt.Fprintf(&sb, "<h3>Findings (%d)</h3><table>", len(b.Review.Findings))
			fmt.Fprintf(&sb, "<tr><th>Severity</th><th>Rule</th><th>Path</th><th>Title</th><th>Suggestion</th></tr>")
			for _, f := range b.Review.Findings {
				fmt.Fprintf(&sb, "<tr><td><span class='tag %s'>%s</span></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>",
					sevClass(string(f.Severity)), f.Severity, html.EscapeString(f.Rule),
					html.EscapeString(f.Path), html.EscapeString(f.Title), html.EscapeString(f.Suggestion))
			}
			sb.WriteString("</table>")
		}
	}
	if len(b.Patterns) > 0 {
		fmt.Fprintf(&sb, "<h2>Patterns (%d)</h2><table>", len(b.Patterns))
		fmt.Fprintf(&sb, "<tr><th>Family</th><th>Severity</th><th>Rule</th><th>Title</th></tr>")
		for _, p := range b.Patterns {
			fmt.Fprintf(&sb, "<tr><td>%s</td><td><span class='tag %s'>%s</span></td><td>%s</td><td>%s</td></tr>",
				p.Family, sevClass(string(p.Severity)), p.Severity, html.EscapeString(p.Rule), html.EscapeString(p.Title))
		}
		sb.WriteString("</table>")
	}
	sb.WriteString("</body></html>")
	return sb.String()
}

func okClass(ok bool) string {
	if ok {
		return "ok"
	}
	return "fail"
}
func sevClass(s string) string {
	switch s {
	case "critical", "high":
		return "crit"
	case "medium":
		return "med"
	case "low":
		return "low"
	}
	return "info"
}
func verdictClass(v string) string {
	switch v {
	case "APPROVE":
		return "ok"
	case "COMMENT":
		return "warn"
	}
	return "fail"
}
