"""DriftDetector — markdown-vs-mirror consistency scan (SPEC D14, §8.2).

Task 12 of data-model-unification: walks the vault, finds each UEID's
markdown source + SQLite mirror row, and emits a DriftFinding per entity.

Findings come in 4 DriftState variants:
- IN_SYNC:        markdown mtime ≈ mirror row mtime
- MARKDOWN_NEWER: .md touched after the row was last written
- SQLITE_NEWER:   mirror row written after the .md was touched
- CONFLICT:       both sides changed AND frontmatter hash differs from
                  the row's snapshot (human review needed)

`scan()` also writes a triagem.md summary to the vault root by default
(SEC/§8.2 contract) so a human operator can see the drift queue.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from ikigai.entities.drift_state import DriftState
from ikigai.propagation.sqlite_adapter import SQLiteAdapter


_TRIAGEM_HEADER = """# Triagem — Drift Detector

Auto-generated by `DriftDetector.scan()`. Do not edit by hand; the next
scan will overwrite this file.

This report surfaces markdown-vs-mirror consistency findings per UEID.
Each finding is either **IN_SYNC** (no action needed), **MARKDOWN_NEWER**
(operator edited the .md after the mirror row was last written — re-mirror
via the agentic writer), **SQLITE_NEWER** (mirror row was updated without
an .md edit — investigate), or **CONFLICT** (both sides changed AND the
frontmatter hash diverges — manual reconciliation required).

| UEID | State | Markdown mtime | SQLite mtime | Markdown path |
|------|-------|----------------|--------------|---------------|
"""


@dataclass(frozen=True)
class DriftFinding:
    ueid: str
    state: DriftState
    source_md_path: Path
    markdown_mtime: datetime | None = None
    sqlite_mtime: datetime | None = None
    note: str = ""


class DriftDetector:
    """Walk the vault, compare mtimes, emit findings.

    Stateless across `scan()` calls; one detector per adapter.
    """

    def __init__(self, adapter: SQLiteAdapter) -> None:
        self._adapter = adapter

    def scan(
        self,
        vault_root: Path,
        *,
        write_triagem: bool = True,
        triagem_path: Path | None = None,
    ) -> Path:
        """Walk `vault_root`, compare each row in `plan_entities` to its
        markdown source. Returns the path to the triagem.md file written
        under `vault_root` (or `triagem_path` if provided).

        `write_triagem=False` skips the file write — handy for tests.
        """
        findings = list(self._collect(vault_root))

        target = triagem_path or (Path(vault_root) / "triagem.md")
        if write_triagem:
            target.write_text(self._render(findings), encoding="utf-8")
        return target

    # ──────── Internals ────────

    def _collect(self, vault_root: Path) -> Iterable[DriftFinding]:
        # Enumerate rows from the mirror; pair with .md files
        for row in self._adapter.list_all():
            ueid = row.get("ueid")
            sp = row.get("source_md_path")
            if not ueid or not sp:
                continue
            md_path = Path(sp)
            if not md_path.is_absolute():
                md_path = vault_root.parent / md_path
            finding = self._classify(ueid, md_path, row)
            if finding is not None:
                yield finding

    def _classify(
        self,
        ueid: str,
        md_path: Path,
        row: dict,
    ) -> DriftFinding | None:
        sql_mtime = self._adapter.mtime_for(ueid)
        if not md_path.exists():
            return DriftFinding(
                ueid=ueid,
                state=DriftState.SQLITE_NEWER,
                source_md_path=md_path,
                sqlite_mtime=sql_mtime,
                note=".md missing — mirror holds state only",
            )
        md_mtime = datetime.fromtimestamp(md_path.stat().st_mtime, tz=timezone.utc)
        if sql_mtime is None:
            return DriftFinding(
                ueid=ueid,
                state=DriftState.MARKDOWN_NEWER,
                source_md_path=md_path,
                markdown_mtime=md_mtime,
                note="no mirror row (orphan markdown)",
            )
        delta = (md_mtime - sql_mtime).total_seconds()
        if abs(delta) < 1.0:
            return DriftFinding(
                ueid=ueid,
                state=DriftState.IN_SYNC,
                source_md_path=md_path,
                markdown_mtime=md_mtime,
                sqlite_mtime=sql_mtime,
            )
        if delta > 0:
            state = DriftState.MARKDOWN_NEWER
        else:
            state = DriftState.SQLITE_NEWER
        # Promote to CONFLICT only if frontmatter content actually differs
        # (left as future task — currently relies on mtime as proxy).
        return DriftFinding(
            ueid=ueid,
            state=state,
            source_md_path=md_path,
            markdown_mtime=md_mtime,
            sqlite_mtime=sql_mtime,
        )

    def _render(self, findings: list[DriftFinding]) -> str:
        rows: list[str] = [_TRIAGEM_HEADER]
        for f in findings:
            md = f.markdown_mtime.isoformat() if f.markdown_mtime else "—"
            sq = f.sqlite_mtime.isoformat() if f.sqlite_mtime else "—"
            rows.append(
                f"| `{f.ueid}` | {f.state.value} | {md} | {sq} | `{f.source_md_path.as_posix()}` |"
            )
        if not findings:
            rows.append("| _(none)_ | — | — | — | — |")
        rows.append("")
        rows.append(f"_Scanned at {datetime.now(timezone.utc).isoformat()}._")
        rows.append("")
        return "\n".join(rows)


__all__ = ["DriftDetector", "DriftFinding"]