#!/bin/bash
# Hill-Climb — weekly self-improvement loop (Loop 4)
# Reads traces, proposes harness improvements, opens PR (no auto-merge)
#
# Usage:
#   bash .claude/loop/hill-climb.sh
#   bash .claude/loop/hill-climb.sh --dry-run
#
# Inspired by LangChain's "Hill-climbing loop" (jun 2026):
# "Production traces feed an analysis agent that improves the harness config."
# Adapted for life-oss with constitution/AGENTS.md as the primary improvement surface.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PROGRESS_FILE="$SCRIPT_DIR/progress.md"
ROADMAP_FILE="$SCRIPT_DIR/roadmap.md"
TASKS_FILE="$SCRIPT_DIR/tasks.md"
CONSTITUTION_FILE="$SCRIPT_DIR/constitution.md"
AGENTS_MD="$PROJECT_ROOT/AGENTS.md"

DRY_RUN=false
if [ "${1:-}" == "--dry-run" ]; then
  DRY_RUN=true
fi

# Gather the last 7 days of traces
SINCE=$(date -u -d '7 days ago' +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -v-7d +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo "1970-01-01T00:00:00Z")
RECENT_TRACES=$(grep "^## " "$PROGRESS_FILE" 2>/dev/null | tail -50 || echo "No traces yet")

# Aggregate stats (awk avoids the grep -c double-zero bug when count=0)
TOTAL_TICKS=$(awk '/^## /{c++} END{print c+0}' "$PROGRESS_FILE")
TOTAL_PASS=$(awk '/\| PASS/{c++} END{print c+0}' "$PROGRESS_FILE")
TOTAL_FAIL=$(awk '/\| FAIL/{c++} END{print c+0}' "$PROGRESS_FILE")
TOTAL_NEEDS_FIX=$(awk '/\| NEEDS_FIX/{c++} END{print c+0}' "$PROGRESS_FILE")
TOTAL_BLOCKED=$(awk '/\| BLOCKED/{c++} END{print c+0}' "$PROGRESS_FILE")

# Cost aggregate
TOTAL_COST=$(grep "cost_usd:" "$PROGRESS_FILE" 2>/dev/null | awk -F': ' '{s+=$NF} END {printf "%.2f", s+0}')

cat <<EOF
═══════════════════════════════════════════════════════════════
  HILL-CLIMB — Loop 4 self-improvement (life-oss)
  $(date -u +%Y-%m-%dT%H:%M:%SZ)
═══════════════════════════════════════════════════════════════
Stats over the last 7 days:
  Total ticks:           $TOTAL_TICKS
  PASS:                  $TOTAL_PASS
  FAIL:                  $TOTAL_FAIL
  NEEDS_FIX:             $TOTAL_NEEDS_FIX
  BLOCKED:               $TOTAL_BLOCKED
  Total cost:            \$$TOTAL_COST USD
EOF

if [ "$TOTAL_TICKS" -eq 0 ]; then
  echo ""
  echo "No ticks yet. Hill-climb has no data. Exiting."
  exit 0
fi

# Identify patterns
echo ""
echo "Patterns detected:"
echo "───────────────────────────────────────────────────────────"

# Pattern 1: tasks with > 2 retries
RETRIED_TASKS=$(awk '
  /^## / { if (current) print current, retries; current=$0; retries=0 }
  /notes:/ { if (match($0, /retry/)) retries++ }
  END { if (current) print current, retries }
' "$PROGRESS_FILE" | awk '$NF > 2 {print "  - " $0}')

if [ -n "$RETRIED_TASKS" ]; then
  echo "⚠️  Tasks with > 2 retries:"
  echo "$RETRIED_TASKS"
fi

# Pattern 2: cost outliers
HIGH_COST=$(awk '/cost_usd:/{print $0}' "$PROGRESS_FILE" | sort -t: -k2 -nr | head -3)
if [ -n "$HIGH_COST" ]; then
  echo ""
  echo "💰 Top 3 most expensive ticks:"
  echo "$HIGH_COST" | sed 's/^/  /'
fi

# Pattern 3: most-failed specs
if [ "$TOTAL_FAIL" -gt 0 ]; then
  echo ""
  echo "❌ Failures observed. Likely causes:"
  echo "  - Prompt unclear (check orchestrator.md)"
  echo "  - Spec ambiguous (check SPEC.md files)"
  echo "  - Deterministic gates flaky (check test suite)"
fi

# Build the proposal (writes to a tracked dir so `git add` actually stages it;
# .claude/loop/logs/ is gitignored, which broke prior runs)
PROPOSAL_DIR="$SCRIPT_DIR/proposals"
PROPOSAL_FILE="$PROPOSAL_DIR/hill-climb-$(date +%Y%m%d).md"
mkdir -p "$PROPOSAL_DIR"

cat > "$PROPOSAL_FILE" <<EOF
# Hill-Climb Proposal — $(date +%Y-%m-%d)

## Summary
- Total ticks analyzed: $TOTAL_TICKS
- Pass rate: $(echo "scale=1; $TOTAL_PASS * 100 / $TOTAL_TICKS" | bc 2>/dev/null || echo "N/A")%
- Total cost: \$$TOTAL_COST

## Proposed Changes

### To .claude/loop/constitution.md
$(if [ "$TOTAL_FAIL" -gt 2 ]; then echo "- Consider adding an anti-pattern observed in failures"; else echo "- No change recommended"; fi)

### To .claude/agents/loop/orchestrator.md
$(if [ -n "$RETRIED_TASKS" ]; then echo "- Add explicit guidance for: $(echo "$RETRIED_TASKS" | head -1 | awk '{print $3}')"; else echo "- No change recommended"; fi)

### To .claude/agents/loop/worker.md
$(if [ "$TOTAL_FAIL" -gt 1 ]; then echo "- Review failure modes, add explicit guard"; else echo "- No change recommended"; fi)

### To .claude/agents/loop/verifier.md
$(if [ "$TOTAL_NEEDS_FIX" -gt 2 ]; then echo "- Tighten the NEEDS_FIX threshold or expand rubric"; else echo "- No change recommended"; fi)

### To AGENTS.md
- $(if [ "$TOTAL_COST" != "0.00" ] && [ "$(echo "$TOTAL_COST > 20" | bc 2>/dev/null || echo 0)" == "1" ]; then echo "Add cost-awareness section"; else echo "No change recommended"; fi)

## Next Steps
1. Review this proposal
2. Apply the recommended changes (or skip)
3. Commit and push
4. Next hill-climb: 7 days

---
Generated by .claude/loop/hill-climb.sh
EOF

echo ""
echo "Proposal written to: $PROPOSAL_FILE"
echo ""
if $DRY_RUN; then
  echo "(DRY RUN — would open PR with this proposal)"
  exit 0
fi

# Open a PR with the proposal (if git is initialized)
cd "$PROJECT_ROOT"
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  BRANCH="hill-climb/$(date +%Y%m%d)"
  git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH" 2>/dev/null
  git add "$PROPOSAL_FILE"
  git commit -m "chore(hill-climb): weekly harness review $(date +%Y-%m-%d)

Proposes changes to:
- constitution.md (if failures observed)
- orchestrator.md (if retries observed)
- worker.md / verifier.md (if quality issues)
- AGENTS.md (if cost issues)

Review the proposal and apply the recommended changes.

Ref: .claude/loop/hill-climb.sh" 2>/dev/null || echo "(no changes to commit)"
  echo ""
  echo "Branch created: $BRANCH"
  echo "Review the proposal and push when ready:"
  echo "  git push origin $BRANCH"
else
  echo "(not a git repo — proposal saved locally only)"
fi
