package review

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// ReportMarkdown renders a Report as markdown suitable for posting on GitHub.
func ReportMarkdown(r *Report) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# medic review — %s PR #%d\n\n", r.Repo, r.PR.Number)
	fmt.Fprintf(&sb, "> **%s** — _%s_\n>\n", r.PR.Title, r.PR.URL)
	fmt.Fprintf(&sb, "> branch `%s` → `%s`  •  author @%s  •  state %s\n\n",
		r.PR.Branch, r.PR.Base, r.PR.Author, r.PR.State)

	fmt.Fprintf(&sb, "**Verdict:** `%s`  •  **Score:** %d/100\n\n", r.Verdict, r.Score)

	fmt.Fprintf(&sb, "## Summary\n\n")
	fmt.Fprintf(&sb, "- %d files changed\n", len(r.Files))
	added, removed := 0, 0
	for _, f := range r.Files {
		added += f.Additions
		removed += f.Deletions
	}
	fmt.Fprintf(&sb, "- +%d / -%d lines\n", added, removed)
	fmt.Fprintf(&sb, "- %d findings\n", len(r.Findings))
	if r.Health != nil {
		fmt.Fprintf(&sb, "- health score: %d/100 (ok=%v)\n", r.Health.Score, r.Health.OK)
	}
	fmt.Fprintln(&sb)

	if len(r.Findings) > 0 {
		fmt.Fprintf(&sb, "## Findings\n\n")
		bySev := groupBySeverity(r.Findings)
		// Stable severity order
		sevOrder := []Severity{SeverityCritical, SeverityHigh, SeverityMedium, SeverityLow, SeverityInfo}
		for _, s := range sevOrder {
			fs := bySev[s]
			if len(fs) == 0 {
				continue
			}
			fmt.Fprintf(&sb, "### %s (%d)\n\n", strings.ToUpper(string(s)), len(fs))
			for _, f := range fs {
				if f.Path != "" {
					fmt.Fprintf(&sb, "- **[%s]** `%s:%d` — %s\n", f.Rule, f.Path, f.Line, f.Title)
				} else {
					fmt.Fprintf(&sb, "- **[%s]** %s\n", f.Rule, f.Title)
				}
				if f.Rationale != "" {
					fmt.Fprintf(&sb, "  - rationale: %s\n", f.Rationale)
				}
				if f.Suggestion != "" {
					fmt.Fprintf(&sb, "  - suggest: %s\n", f.Suggestion)
				}
			}
			fmt.Fprintln(&sb)
		}
	}

	if r.Health != nil && len(r.Health.Checks) > 0 {
		fmt.Fprintf(&sb, "## Health\n\n")
		for _, c := range r.Health.Checks {
			icon := "✓"
			switch c.Severity {
			case "warn":
				icon = "⚠"
			case "fail":
				icon = "✗"
			}
			fmt.Fprintf(&sb, "- %s **%s** (%s) — %s\n", icon, c.Name, c.Kind, c.Err)
		}
		fmt.Fprintln(&sb)
	}

	if len(r.Files) > 0 {
		fmt.Fprintf(&sb, "## Files\n\n")
		fmt.Fprintf(&sb, "| File | + | − |\n|---|---:|---:|\n")
		// Sort by net change descending
		files := append([]File(nil), r.Files...)
		sort.Slice(files, func(i, j int) bool {
			return (files[i].Additions - files[i].Deletions) > (files[j].Additions - files[j].Deletions)
		})
		for _, f := range files {
			fmt.Fprintf(&sb, "| `%s` | %d | %d |\n", f.Path, f.Additions, f.Deletions)
		}
		fmt.Fprintln(&sb)
	}

	fmt.Fprintf(&sb, "\n<sub>generated by medic 🩺 at %s</sub>\n", time.Now().Format(time.RFC3339))
	return sb.String()
}

// ReportSARIF renders a Report as SARIF 2.1.0 for IDE integration.
func ReportSARIF(r *Report) string {
	var sb strings.Builder
	sb.WriteString(`{"version":"2.1.0","$schema":"https://json.schemastore.org/sarif-2.1.0.json","runs":[`)
	fmt.Fprintf(&sb, `{"tool":{"driver":{"name":"medic","version":"0.1.0","informationUri":"https://github.com/life-oss/medic"}}`)
	sb.WriteString(`,"originalUriBaseIds":{"REPO":{"uri":"https://github.com/` + r.Repo + `/blob/HEAD/"}}`)
	sb.WriteString(`,"results":[`)
	for i, f := range r.Findings {
		if i > 0 {
			sb.WriteString(",")
		}
		level := mapLevel(f.Severity)
		fmt.Fprintf(&sb, `{"ruleId":%q,"level":%q,"message":{"text":%q}`, f.Rule, level, f.Title)
		if f.Path != "" {
			fmt.Fprintf(&sb, `,"locations":[{"physicalLocation":{"artifactLocation":{"uri":%q,"uriBaseId":"REPO"},"region":{"startLine":%d}}}]`, f.Path, f.Line)
		}
		sb.WriteString("}")
	}
	sb.WriteString(`]}]}`)
	return sb.String()
}

func mapLevel(s Severity) string {
	switch s {
	case SeverityCritical, SeverityHigh:
		return "error"
	case SeverityMedium:
		return "warning"
	default:
		return "note"
	}
}

func groupBySeverity(fs []Finding) map[Severity][]Finding {
	out := map[Severity][]Finding{}
	for _, f := range fs {
		out[f.Severity] = append(out[f.Severity], f)
	}
	return out
}
